version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "cargo"
      directory: "/native_locator"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/pythonExtensionApi"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "pip"
      directory: "/python_files/jedilsp_requirements"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: increase
